from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parent
def f(s): return '<div class="formula">'+s+'</div>'
def p(s): return '<p>'+s+'</p>'
def ul(*s): return '<ul>'+''.join('<li>'+x+'</li>' for x in s)+'</ul>'
questions = [
(1,1,'强化学习中的智能体','_____ 是作出智能决策的主体，也是 RL 的学习者。其目标是最大化收到的总收益。',['环境','智能体','策略','奖励'],1,
p('智能体（Agent）是学习与决策的主体。它观察状态，依据策略选择动作，并利用环境反馈改进决策。环境是交互对象；策略是动作选择规则；奖励是反馈信号，三者都不是题目中的学习者。')+f('s<sub>t</sub> → 选择 a<sub>t</sub> → 环境返回 (r<sub>t+1</sub>, s<sub>t+1</sub>)')+p('强化学习通常追求期望长期回报，而不是让当前一步的奖励尽可能大。')+f('G<sub>t</sub> = r<sub>t+1</sub> + γr<sub>t+2</sub> + γ²r<sub>t+3</sub> + ⋯'),
'回报、价值与奖励',p('奖励是单步反馈；回报是一条轨迹上的累积奖励；状态价值是给定策略后、从某状态出发的期望回报。')+f('V<sup>π</sup>(s) = E<sub>π</sub>[G<sub>t</sub> | S<sub>t</sub> = s]')+p('一次行动可能先付出成本，再获得更大的未来收益。应使用长期价值比较动作。')),
(1,2,'强化学习中的环境','与智能体交互的所有内容都称为 _____。',['环境','动作','模型','策略'],0,
p('环境（Environment）是智能体之外、与智能体交互的系统。它接收动作，产生下一状态和奖励。动作只是智能体的行为；模型是对转移和奖励规律的描述；策略是智能体的决策规则。')+ul('机器人：控制程序可作为智能体，地面、障碍物以及被控制的物理机体可作为环境。','下棋：下棋程序作为智能体，棋局和对手的反应作为环境的一部分。')+f('智能体 ── 动作 a<sub>t</sub> ──→ 环境<br>智能体 ←── 状态 s<sub>t+1</sub> 与奖励 r<sub>t+1</sub> ── 环境'),
'智能体边界与可观测性',p('智能体与环境的边界由建模方式决定，并不必然等于机器人外壳。状态（State）与观测（Observation）也不完全相同：传感器读数可能只包含真实状态的一部分。若观测缺少决策所需信息，可以加入历史、速度等变量，或使用部分可观测模型。')),
(1,3,'强化学习的核心思想','_____ 的核心思想是，智能体（AI）与环境交互，接收奖励（正面的或负面的），并根据奖励情况提升自身的决策能力，以期获得最高的累积收益。',['启发式搜索','监督学习','深度学习','强化学习'],3,
p('题干包含智能体、环境、奖励、决策与累积收益，描述的是强化学习（Reinforcement Learning）。智能体通过试错获得经验，再改进策略。')+f('观察状态 → 选择动作 → 接收奖励与下一状态 → 学习 → 再次交互')+f('π* ∈ arg max<sub>π</sub> E<sub>π</sub>[G<sub>0</sub>]')+p('这里的期望采用给定的初始状态分布。启发式搜索用启发函数指导搜索；监督学习学习输入到标签的映射；深度学习使用多层神经网络，能够与强化学习结合形成深度强化学习。')+p('迷宫示例：每步奖励 −0.1，撞墙额外惩罚 −1，到达终点奖励 +100。智能体通过尝试学习能够获得较高回报的路径。'),
'延迟奖励与信用分配',p('奖励可能在许多动作之后才出现。信用分配问题就是判断之前哪些动作促成了结果。奖励设计也会影响学到的行为：若每走一步都得到正奖励，智能体可能偏好绕圈而不是到达终点。奖励应与任务目标一致。')),
(1,4,'强化学习是否需要标签','强化学习的训练样本集中，需要给出“标签”数据。',['对','错'],1,
p('本题为错。标准强化学习不要求为每个状态提供“正确动作”标签，而是通过奖励学习哪些行为能带来更高的长期收益。')+ul('监督学习：图片 → “猫”这一标签。','强化学习：状态 → 采取动作 → 观察奖励与下一状态。')+p('奖励评价行为的结果，通常不能直接告诉智能体当前最优动作是什么。例如撞墙得到 −10，智能体还需要结合其他经验判断应该怎样走。'),
'奖励不是动作标签，但 RL 可以结合监督信号',p('典型经验可以写为 (s, a, r, s′, done)。离线强化学习也可使用事先采集的交互数据；“不需要正确动作标签”不等于“不需要数据”。模仿学习、辅助监督任务或人类反馈可与 RL 结合，因此也不应说强化学习绝对不能使用标签。')+p('TD 学习会构造学习目标，例如 y = r + γV(s′)。这种由经验构造的目标，不是人工标注的正确动作。终止转移通常不再加下一状态价值。')),
(1,5,'ε-贪心动作选择','在 ε-贪心动作选择中，对于两个动作且 ε = 0.5 的情况，选择贪心动作的概率是多少？',['0.25','0.75','1','0'],1,
'<p class="note">题干修复：原材料中的 ε = 0. 被截断；依据你提供的解题过程恢复为 ε = 0.5。采用唯一贪心动作、探索时从所有动作中均匀抽样的标准约定。</p>'+p('ε-greedy 平衡探索与利用：以 1 − ε 的概率利用当前估计，选择贪心动作；以 ε 的概率从所有动作中随机选一个。探索时仍然可能抽到贪心动作。')+f('P(贪心动作) = (1 − ε) + ε / n')+f('= (1 − 0.5) + 0.5 / 2 = 0.5 + 0.25 = <strong>0.75</strong>')+p('例如 Q(s,a₁) = 10，Q(s,a₂) = 6，则 a₁ 是当前的贪心动作。但 a₂ 可能因样本不足被低估，因此需要探索。')+p('若 ε = 0.2 且 n = 4，贪心动作概率是 0.85，每个非贪心动作的概率是 0.05，总和为 1。'),
'并列最优与另一种探索约定',p('若 n 个动作中有 k 个并列贪心动作，且利用阶段也在这 k 个动作中均匀抽样，则每个贪心动作概率为 (1 − ε)/k + ε/n，选中任意贪心动作的总概率为 1 − ε + εk/n。')+p('若另行规定探索时只选非贪心动作，则唯一贪心动作的概率为 1 − ε。这不是本题使用的约定。')),
(2,1,'马尔可夫性','马尔可夫性是指系统的下一个状态只与 ______ 有关，而与来到当前状态的路径无关。',['初始状态','当前状态','当前状态的前一个状态','终止状态'],1,
p('马尔可夫性（Markov Property）表示：给定当前状态后，过去历史不再为下一状态的预测提供额外信息。当前状态应包含预测所需的信息。')+f('P(S<sub>t+1</sub> | S<sub>t</sub>, S<sub>t−1</sub>, …, S<sub>0</sub>) = P(S<sub>t+1</sub> | S<sub>t</sub>)')+p('在有动作的 MDP 中，转移分布还要以当前动作为条件：')+f('P(S<sub>t+1</sub> | S<sub>t</sub>, A<sub>t</sub>, 历史) = P(S<sub>t+1</sub> | S<sub>t</sub>, A<sub>t</sub>)')+p('机器人位于 (3,4)，若位置和动作足以决定转移规律，那么此前从哪条路径到达 (3,4) 不再影响下一状态分布。初始状态、前一个状态和终止状态都不是该定义中所指的条件。'),
'“只依赖现在”不等于未来确定',p('马尔可夫性描述条件概率分布，并不要求转移是确定性的。相同状态与动作可以产生多个随机结果。若机器人的速度影响运动，仅用位置作为状态可能不满足马尔可夫性；加入速度后，状态表示可能更充分。')),
(2,2,'折扣因子的性质','下列关于马尔可夫决策过程中的折扣因子的说法哪个是不正确的？',['折扣因子可以大于 1','可以用于避免马尔可夫过程中的循环导致的无限奖励','折扣因子等于 0 时意味着只考虑即时奖励','折扣因子可以帮助获得良好的数学性质'],0,
p('按本课程标准折扣回报的定义，γ 通常在 [0,1] 内；无限时域折扣任务通常取 0 ≤ γ &lt; 1，因此不正确的是 A。')+f('G<sub>t</sub> = R<sub>t+1</sub> + γR<sub>t+2</sub> + γ²R<sub>t+3</sub> + ⋯')+ul('B：在奖励有界且 γ &lt; 1 时，折扣可使无限循环中的累积回报有界。每步奖励 1，γ = 0.9 时，G = 1/(1 − 0.9) = 10。','C：γ = 0 时，Gₜ = Rₜ₊₁，只考虑即时奖励。','D：在标准有限 MDP、γ &lt; 1 的条件下，Bellman 算子具有压缩性质，有助于保证唯一不动点与迭代收敛。')+f('|R<sub>t</sub>| ≤ R<sub>max</sub> ⇒ |G<sub>t</sub>| ≤ R<sub>max</sub> / (1 − γ)')+p('γ 越大，未来奖励的权重越大。若 γ &gt; 1，远期权重会增长；例如每步奖励 1 的无限过程将发散。'),
'γ = 1 的边界条件',p('有限时域任务可以取 γ = 1。对于随机长度的回合任务，即使最终几乎必然终止，也仍需适当的可积性条件才能保证期望回报有限，例如奖励有界且期望回合长度有限。“会终止”本身不是所有收敛结论的充分条件。')),
(2,3,'状态转移矩阵','马尔可夫过程中的状态转移矩阵每一行的和可以不为 1。',['对','错'],1,
p('采用行表示当前状态、列表示下一状态的约定，完整状态空间上的转移矩阵每行是一个概率分布，因此必须非负且和为 1。')+f('P<sub>ij</sub> = P(S<sub>t+1</sub> = j | S<sub>t</sub> = i)<br>0 ≤ P<sub>ij</sub> ≤ 1，　∑<sub>j=1</sub><sup>n</sup> P<sub>ij</sub> = 1')+'<table><caption>合法转移矩阵示例</caption><thead><tr><th>当前状态</th><th>到 S₁</th><th>到 S₂</th><th>到 S₃</th><th>行和</th></tr></thead><tbody><tr><th>S₁</th><td>0.2</td><td>0.5</td><td>0.3</td><td>1</td></tr><tr><th>S₂</th><td>0.1</td><td>0.7</td><td>0.2</td><td>1</td></tr><tr><th>S₃</th><td>0.4</td><td>0.1</td><td>0.5</td><td>1</td></tr></tbody></table>'+p('第一列之和为 0.7，第二列为 1.3，第三列为 1。列和一般不必等于 1。'),
'终止状态与次随机矩阵',p('把终止状态纳入完整矩阵并设为吸收态，可令 P(终止→终止) = 1。如果只保留非终止状态，则得到子矩阵，每行和可能小于 1；缺少的概率对应进入终止状态。这不反驳完整转移矩阵的行和规则。另有文献使用列随机约定，阅读时应先看下标定义。')),
(2,4,'直接求解状态价值的复杂度','对于含有 n 个状态的马尔可夫奖励过程，其状态价值可以通过直接求解方程组获得，计算复杂度为？',['O(n)','O(n²)','O(n³)','O(n⁴)'],2,
p('马尔可夫奖励过程（MRP）的 Bellman 方程把当前价值拆为一步期望奖励与折扣后的下一状态价值。')+f('V = R + γPV<br>(I − γP)V = R<br>V = (I − γP)<sup>−1</sup>R')+p('V 是 n 维价值向量，R 是一步期望奖励向量，P 是 n × n 转移矩阵，I 是单位矩阵。经典稠密高斯消元或 LU 分解的时间复杂度为 O(n³)，所以选 C。')+p('n² 是矩阵元素数量，但消元还需逐轮更新子矩阵。累计运算量与 1² + 2² + ⋯ + n² 同阶，因此是 O(n³)。'),
'求解线性系统，而不是显式求逆',p('公式中的逆矩阵主要用于理论表达。实现时通常直接求解 (I − γP)V = R，以避免显式求逆的额外开销。对于行随机 P 和 γ &lt; 1，该矩阵可逆；γ = 1 时不能无条件套用逆矩阵公式。')+p('稠密存储需要 O(n²) 空间。稀疏或特殊结构可能降低成本，O(n³) 指经典一般稠密直接法。迭代评估使用 Vₖ₊₁ = R + γPVₖ；稠密一次更新约 O(n²)，总成本还取决于达到精度需要多少次迭代。大型问题也可采用 MC、TD 或函数近似。')),
(2,5,'最优策略是否唯一','马尔可夫决策过程中的最优策略是唯一的。',['对','错'],1,
p('本题为错。不同策略可以实现相同的最优价值。考虑两个动作都立即获得 10 并终止：')+f('Q*(s,A) = 10，　Q*(s,B) = 10')+p('始终选 A 与始终选 B 是两个不同的确定性策略，但都达到 V*(s) = 10。以 0.3 的概率选 A、0.7 的概率选 B，也获得同样价值。')+f('V*(s) = max<sub>π</sub> V<sup>π</sup>(s)<br>π*(s) ∈ arg max<sub>a</sub> Q*(s,a)')+p('arg max 返回取得最大值的动作集合，而 max 返回最大值本身。多个动作可以共享一个最大值。'),
'唯一价值与多种最优策略',p('在标准有限状态、有限动作、奖励有界且 γ &lt; 1 的 MDP 中，最优价值函数是唯一的，且存在确定性平稳最优策略；但该策略未必唯一。若每个状态只在达到 Q* 最大值的动作上分配概率，可得到随机最优策略。')+p('注意，“两个动作价值相同”还不够，它们必须都达到最大值。例如价值为 5、5、10 的三个动作中，前两个虽然相等，却不是最优动作。')),
]

def render(q):
    hw,num,title,stem,opts,ans,body,ext,extra=q
    option_html=''.join('<li><b>'+chr(65+i)+'.</b> '+escape(x)+'</li>' for i,x in enumerate(opts))
    return f'''<article class="question" id="hw{hw}-q{num}"><div class="eyebrow">作业 {hw} / 第 {num:02d} 题 · {'判断题' if len(opts)==2 else '单选题'}</div><h3>{title}</h3><p class="stem">{stem}</p><ol class="options">{option_html}</ol><details open class="solution"><summary>答案与解析</summary><div class="answer">{chr(65+ans)}. {opts[ans]}</div><h4>解析</h4>{body}<aside class="extension"><h4>拓展 · {ext}</h4>{extra}</aside></details></article>'''

nav=''.join(f'<a href="#hw{q[0]}-q{q[1]}"><span>{q[0]}.{q[1]}</span> {q[2]}</a>' for q in questions)
sections=''
for hw,title,desc in [(1,'强化学习基础','从智能体与环境出发，理解奖励、回报与探索。'),(2,'马尔可夫决策过程','从马尔可夫性走向 Bellman 方程与最优策略。')]:
    rows=''.join(f'<tr><th>{q[1]}</th><td>{chr(65+q[5])}. {q[4][q[5]]}</td><td><a href="#hw{hw}-q{q[1]}">{q[2]}</a></td></tr>' for q in questions if q[0]==hw)
    sections+=f'<section id="hw{hw}" class="homework"><div class="eyebrow">ASSIGNMENT 0{hw}</div><h2>作业 {hw} · {title}</h2><p class="muted">{desc}</p><details class="overview" open><summary>答案速查 · 5 题</summary><table><thead><tr><th>题号</th><th>答案</th><th>知识点</th></tr></thead><tbody>{rows}</tbody></table></details>'+''.join(render(q) for q in questions if q[0]==hw)+'</section>'

html='''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="强化学习前两次作业：10 道题目、答案、逐题解析与拓展知识，附 ε-greedy 与折扣回报交互演示。"><title>强化学习 · 作业与知识笔记</title><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#main">跳到正文</a><header><a class="brand" href="#">RL<span> / 学习笔记</span></a><div class="header-actions"><button id="study" type="button" aria-pressed="false">自测模式</button><button id="print" type="button">打印 / PDF</button></div></header><div class="layout"><nav aria-label="作业目录"><div class="eyebrow">CONTENTS / 目录</div><a class="nav-section" href="#hw1">01 强化学习基础</a>'''+nav.split('<a href="#hw2-q1">')[0]+'''<a class="nav-section" href="#hw2">02 马尔可夫决策过程</a><a href="#hw2-q1">'''+nav.split('<a href="#hw2-q1">')[1]+'''<a class="nav-section" href="#lab">03 参数实验室</a><a class="nav-section" href="#recap">04 复习清单</a><a href="#notes">整理说明与参考</a></nav><main id="main"><section class="hero"><div class="eyebrow">REINFORCE LEARNING / 强化学习</div><h1>从交互中学习，<br><em>从回报中决策。</em></h1><p>前两次作业整理 · 题目、答案、解析与拓展知识</p><div class="stats"><span><strong>02</strong> 次作业</span><span><strong>10</strong> 道习题</span><span><strong>02</strong> 个交互实验</span></div><div class="flow" aria-label="强化学习交互">智能体 <span>── 动作 →</span> 环境 <span>── 状态、奖励 →</span> 智能体</div></section><p class="reading-note">阅读建议：先尝试作答，再展开解析。切换“自测模式”可同时隐藏答案汇总和逐题解析。数学表达直接随页面显示，无需联网加载公式库。</p>'''+sections+'''
<section id="lab"><div class="eyebrow">LEARN BY CHANGING</div><h2>参数实验室</h2><div class="lab-grid"><article class="lab"><h3>ε-greedy 概率</h3><p>假设存在唯一贪心动作，探索时在所有动作中均匀抽样。</p><label for="epsilon">探索概率 ε <output id="eps-out">0.50</output></label><input id="epsilon" type="range" min="0" max="1" step="0.01" value="0.5"><label for="actions">动作数量 n</label><input id="actions" type="number" min="2" max="100" step="1" value="2"><div class="probbar" aria-hidden="true"><span id="exploit"></span><span id="explore"></span></div><p class="legend">深绿：直接利用 · 浅绿：探索碰巧选中贪心动作</p><div id="eps-result" class="result" aria-live="polite"></div></article><article class="lab"><h3>折扣如何改变未来？</h3><p>每一步奖励均为 1，比较前 10 步回报与无限时域回报。</p><label for="gamma">折扣因子 γ <output id="gamma-out">0.90</output></label><input id="gamma" type="range" min="0" max="1" step="0.01" value="0.9"><div class="discount-bars" id="discount-bars" aria-hidden="true"></div><p class="legend">第 1 至第 10 步奖励的权重：1, γ, γ², …</p><div id="gamma-result" class="result" aria-live="polite"></div></article></div><noscript><p>参数演示需要启用 JavaScript；所有题目与解析仍可直接阅读。</p></noscript></section>
<section id="recap"><div class="eyebrow">CONNECT THE CONCEPTS</div><h2>把知识串起来</h2><div class="concepts"><p><b>MP · 马尔可夫过程</b><br>状态 + 转移规律</p><p><b>MRP · 马尔可夫奖励过程</b><br>MP + 奖励 + 折扣因子</p><p><b>MDP · 马尔可夫决策过程</b><br>MRP + 动作与决策</p></div><p>给定平稳策略 π 后，MDP 会诱导一个 MRP。其转移矩阵为 P<sup>π</sup>(s,s′) = ∑<sub>a</sub> π(a|s)P(s′|s,a)，奖励为 R<sup>π</sup>(s) = ∑<sub>a</sub> π(a|s)R(s,a)。策略评估求 V<sup>π</sup>；控制问题寻找最优策略。</p><table><caption>概念速记</caption><thead><tr><th>概念</th><th>英文</th><th>含义</th></tr></thead><tbody><tr><td>智能体</td><td>Agent</td><td>学习与决策的主体</td></tr><tr><td>环境</td><td>Environment</td><td>与智能体交互的系统</td></tr><tr><td>状态</td><td>State</td><td>用于描述当前情况的信息</td></tr><tr><td>动作</td><td>Action</td><td>智能体采取的行为</td></tr><tr><td>奖励</td><td>Reward</td><td>单步反馈</td></tr><tr><td>策略</td><td>Policy</td><td>动作选择规则 π(a|s)</td></tr><tr><td>回报</td><td>Return</td><td>累积的折扣奖励 Gₜ</td></tr><tr><td>价值</td><td>Value</td><td>给定策略的期望回报</td></tr></tbody></table><table><caption>易考判断 · 注意条件</caption><thead><tr><th>说法</th><th>判断</th></tr></thead><tbody><tr><td>马尔可夫性表示已知当前状态后，历史不再提供额外预测信息</td><td>对；MDP 还需给定当前动作</td></tr><tr><td>未来只依赖初始状态</td><td>错</td></tr><tr><td>完整的行随机转移矩阵每行和为 1</td><td>对</td></tr><tr><td>状态转移矩阵每列和必须为 1</td><td>错</td></tr><tr><td>标准折扣因子通常位于 [0,1]</td><td>对</td></tr><tr><td>γ = 0 时只关心即时奖励</td><td>对</td></tr><tr><td>γ 越接近 1，未来奖励的相对权重越大</td><td>对</td></tr><tr><td>经典稠密直接法求解 n 元线性系统为 O(n³)</td><td>对</td></tr><tr><td>不同最优策略会得到不同的最优价值函数</td><td>错</td></tr><tr><td>最优策略一定唯一</td><td>错</td></tr><tr><td>多个动作同时达到最大 Q* 时，可能有多个最优策略</td><td>对</td></tr></tbody></table></section>
<section id="notes" class="notes"><h2>整理说明与参考</h2><p>题目及原始答案来自用户提供的两次作业。解析经过重组与符号修复；各题“拓展”及参数实验为补充内容。未获得课程原始题目文件。</p><ul><li>作业 1 第 5 题根据所附解析恢复 ε = 0.5；作业 2 第 4 题恢复状态数 n 及 O(n³) 等缺失符号。</li><li>统一修复 sₜ、aₜ、rₜ₊₁、γ、π* 等截断表达；奖励与下一状态均由环境返回智能体。</li><li>为折扣回报收敛、转移矩阵行和、矩阵可逆性及最优价值唯一性补充适用条件。</li><li>经典定义与进一步阅读：Sutton &amp; Barto，<a href="https://www.incompleteideas.net/book/bookdraft2018mar21.pdf">Reinforcement Learning: An Introduction, 2nd edition</a>，第 1–4 章（交互框架、多臂老虎机、有限 MDP 与动态规划）。</li></ul></section><footer>强化学习 / Reinforce Learning <span>理解 · 推导 · 复习</span></footer></main></div></body></html>'''
(ROOT/'index.html').write_text(html,encoding='utf-8')
print('Generated index.html with',len(questions),'questions')
